package topcoder;
import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM164_Div2_L2_PartySeats
{
	public String[] seating(String[] attendees)
	{
        int n = attendees.length;
        if (n % 4 != 0) return new String[0];

        ArrayList<String> girl = new ArrayList<String>();
        ArrayList<String> boy = new ArrayList<String>();     
        for (int i = 0; i < n; i++)
        {
            String[] s = attendees[i].split(" ");
            if (s[1].equals("boy"))
                boy.add(s[0]);
            else
                girl.add(s[0]);
        }
        if (boy.size() != girl.size()) return new String[0];
        //b & g are equal and even

        Collections.sort(boy);
        Collections.sort(girl);
        String[] a = new String[n + 2];
        int ind = 0;
        a[ind++] = "HOST";
        int b = 0, g = 0;
        for (int i = 0; i < n/2; i++)
            if (i % 2 == 0)
                a[ind++] = girl.get(g++);
            else
                a[ind++] = boy.get(b++);
        a[ind++] = "HOSTESS";
        for (int i = 0; i < n/2; i++)
            if (i % 2 == 1)
                a[ind++] = girl.get(g++);
            else
                a[ind++] = boy.get(b++);
        
        return a;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, boolean hasAnswer, String[] p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		SRM164_Div2_L2_PartySeats obj;
		String[] answer;
		obj = new SRM164_Div2_L2_PartySeats();
		long startTime = System.currentTimeMillis();
		answer = obj.seating(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print("\"" + p1[i] + "\"");
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + answer[i] + "\"");
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (!answer[i].equals(p1[i])) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		
		// ----- test 0 -----
		p0 = new String[]{"BOB boy","SAM girl","DAVE boy","JO girl"};
		p1 = new String[]{"HOST","JO","BOB","HOSTESS","DAVE","SAM"};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"JOHN boy"};
		p1 = new String[]{};
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"JOHN boy","CARLA girl"};
		p1 = new String[]{};
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"BOB boy","SUZIE girl","DAVE boy","JO girl","AL boy","BOB boy","CARLA girl","DEBBIE girl"};
		p1 = new String[]{"HOST","CARLA","AL","DEBBIE","BOB","HOSTESS","BOB","JO","DAVE","SUZIE"};
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
