package topcoder;
//import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM458_Div2_L1_Desertification
{
	public int desertArea(String[] island, int T)
	{
        int r = island.length;
        int c = island[0].length();
        int cnt = 0;

        for (int i = 0; i < r; i++)
            for (int j = 0; j < c; j++)
            {
                boolean desert = false;
                for (int x = 0; x < r; x++)
                    for (int y = 0; y < c; y++)
                        if (Math.abs(i-x) + Math.abs(j-y) <= T)
                        {
                            if (island[x].charAt(y) == 'D')
                                desert = true;
                        }
                if (desert) cnt++;                
            }

        return cnt;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, int p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + p1);
		System.out.println("]");
		SRM458_Div2_L1_Desertification obj;
		int answer;
		obj = new SRM458_Div2_L1_Desertification();
		long startTime = System.currentTimeMillis();
		answer = obj.desertArea(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		int p2;
		
		// ----- test 0 -----
		p0 = new String[]{"FFF","FDF","FFF"};
		p1 = 1;
		p2 = 5;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"FFF","FDF","FFF"};
		p1 = 2;
		p2 = 9;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"FFFFF","FFDFF","FFFFD","FFFFF","FFFFF"};
		p1 = 2;
		p2 = 17;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"FFFFFF","FFFFFF","FFFFFF","FFFFFF"};
		p1 = 1000000000;
		p2 = 0;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"FFFFFDFFFF","FDFDFFFFFF","FFFFFFFFFD","FFFFFFFFFF","DDFFFFFFFF","FFFFFFFFFD","FFFFFFFFFF","FFFFFFFDFF","FFFFFFFDFF","FFFFDDFFFF"};
		p1 = 3;
		p2 = 90;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new String[]{"FFFFFDFFFF","FDFDFFFFFF","FFFFFFFFFD","FFFFFFFFFF","DDFFFFFFFF","FFFFFFFFFD","FFFFFFFFFF","FFFFFFFDFF","FFFFFFFDFF","FFFFDDFFFF"};
		p1 = 98765432;
		p2 = 100;
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
