package topcoder;
//import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM478_Div2_L1_KiwiJuiceEasy
{
	public int[] thePouring(int[] capacities, int[] bottles, int[] fromId, int[] toId)
	{
        int n = fromId.length;
        for (int i = 0; i < n; i++)
        {
            int dif = capacities[toId[i]] - bottles[toId[i]];
            if (dif >= bottles[fromId[i]])
            {
                bottles[toId[i]] += bottles[fromId[i]];
                bottles[fromId[i]] = 0;
            }
            else
            {
                bottles[toId[i]] += dif;
                bottles[fromId[i]] -= dif;
            }
        }
        return bottles;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, int[] p2, int[] p3, boolean hasAnswer, int[] p4) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p3.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p3[i]);
		}
		System.out.print("}");
		System.out.println("]");
		SRM478_Div2_L1_KiwiJuiceEasy obj;
		int[] answer;
		obj = new SRM478_Div2_L1_KiwiJuiceEasy();
		long startTime = System.currentTimeMillis();
		answer = obj.thePouring(p0, p1, p2, p3);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p4.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print(p4[i]);
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(answer[i]);
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p4.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (answer[i] != p4[i]) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int[] p1;
		int[] p2;
		int[] p3;
		int[] p4;
		
		// ----- test 0 -----
		p0 = new int[]{20,20};
		p1 = new int[]{5,8};
		p2 = new int[]{0};
		p3 = new int[]{1};
		p4 = new int[]{0,13};
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{10,10};
		p1 = new int[]{5,8};
		p2 = new int[]{0};
		p3 = new int[]{1};
		p4 = new int[]{3,10};
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{30,20,10};
		p1 = new int[]{10,5,5};
		p2 = new int[]{0,1,2};
		p3 = new int[]{1,2,0};
		p4 = new int[]{10,10,0};
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{14,35,86,58,25,62};
		p1 = new int[]{6,34,27,38,9,60};
		p2 = new int[]{1,2,4,5,3,3,1,0};
		p3 = new int[]{0,1,2,4,2,5,3,1};
		p4 = new int[]{0,14,65,35,25,35};
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{700000,800000,900000,1000000};
		p1 = new int[]{478478,478478,478478,478478};
		p2 = new int[]{2,3,2,0,1};
		p3 = new int[]{0,1,1,3,2};
		p4 = new int[]{0,156956,900000,856956};
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
