package topcoder;
//import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM562_Div2_L2_PastingPaintingDivTwo
{
	public long countColors(String[] clipboard, int T)
	{
        int[][] a = new int[100][100];
        int[][] b = new int[100][100];
        int H = clipboard.length;
        int W = clipboard[0].length();

        for (int i = 1; i <= H; i++)
            for (int j = 1; j <= W; j++)
                if (clipboard[i - 1].charAt(j - 1) == 'B')
                    a[i][j] = 1;                

        int min = Math.min(H, W);
        int T2 = Math.min(T, min);

        long sum = 0;
        int diff=0;
        for (int n = 0; n < T2; n++)
            for (int i = 1; i <= H; i++)
                for (int j = 1; j <= W; j++)
                    if (a[i][j] == 1)
                    {
                        if (n == T2 - 1 && b[i + n][j + n] == 0)
                            diff++;
                        b[i + n][j + n] = 1;
                    }

        for (int i = 1; i < 100; i++)
            for (int j = 1; j < 100; j++)
                sum += b[i][j];

        if (T <= T2)
            return sum;

        sum += (long)(T - T2) * diff;
        return sum;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, int p1, boolean hasAnswer, long p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + p1);
		System.out.println("]");
		SRM562_Div2_L2_PastingPaintingDivTwo obj;
		long answer;
		obj = new SRM562_Div2_L2_PastingPaintingDivTwo();
		long startTime = System.currentTimeMillis();
		answer = obj.countColors(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		long p2;
		
		// ----- test 0 -----
		p0 = new String[]{"..B","B..","BB."};
		p1 = 3;
		p2 = 10L;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"B...","....","....","...B"};
		p1 = 2;
		p2 = 4L;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"BBB"};
		p1 = 10000;
		p2 = 30000L;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"."};
		p1 = 1000000000;
		p2 = 0L;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"BB.",".B."};
		p1 = 100;
		p2 = 201L;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new String[]{"..........B..........",".........B.B.........","........B...B........",".......B.....B.......","......B..B.B..B......",".....B...B.B...B.....","....B...........B....","...B...B.....B...B...","..B.....BBBBBB....B..",".B..........BB.....B.","BBBBBBBBBBBBBBBBBBBBB"};
		p1 = 1000000000;
		p2 = 21000000071L;
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
