package topcoder;
import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM679_Div2_L1_ListeningSongs
{
	public int listen(int[] d1, int[] d2, int m, int T)
	{
		Arrays.sort(d1);
		Arrays.sort(d2);
		int n1 = d1.length, n2 = d2.length;
		if (n1 < T || n2 < T)
			return -1;
		
		int sum = 0;
		for (int i = 0; i < T; i++)
			sum += d1[i] + d2[i];
		if (sum > m*60) return -1;
		
		ArrayList<Integer> al = new ArrayList<>();
		for (int i = T; i < n1; i++)
			al.add(d1[i]);
		for (int i = T; i < n2; i++)
			al.add(d2[i]);
		
		int cnt = T*2;
		Collections.sort(al);
		for (int x : al)
		{
			if (sum + x <= m*60)
			{
				sum += x;
				cnt++;
			}
			else break;
		}
		
		return cnt;			
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, int p2, int p3, boolean hasAnswer, int p4) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}" + "," + p2 + "," + p3);
		System.out.println("]");
		SRM679_Div2_L1_ListeningSongs obj;
		int answer;
		obj = new SRM679_Div2_L1_ListeningSongs();
		long startTime = System.currentTimeMillis();
		answer = obj.listen(p0, p1, p2, p3);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p4);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p4;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int[] p1;
		int p2;
		int p3;
		int p4;
		
		// ----- test 0 -----
		p0 = new int[]{300,200,100};
		p1 = new int[]{400,500,600};
		p2 = 17;
		p3 = 1;
		p4 = 4;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{300,200,100};
		p1 = new int[]{400,500,600};
		p2 = 10;
		p3 = 1;
		p4 = 2;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{60,60,60};
		p1 = new int[]{60,60,60};
		p2 = 5;
		p3 = 2;
		p4 = 5;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{120,120,120,120,120};
		p1 = new int[]{60,60,60,60,60,60};
		p2 = 10;
		p3 = 3;
		p4 = 7;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new int[]{196,147,201,106,239,332,165,130,205,221,248,108,60};
		p1 = new int[]{280,164,206,95,81,383,96,255,260,244,60,313,101};
		p2 = 60;
		p3 = 3;
		p4 = 22;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new int[]{100,200,300};
		p1 = new int[]{100,200,300};
		p2 = 2;
		p3 = 1;
		p4 = -1;
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		// ----- test 6 -----
		p0 = new int[]{100,200,300,400,500,600};
		p1 = new int[]{100,200};
		p2 = 1000;
		p3 = 3;
		p4 = -1;
		all_right = KawigiEdit_RunTest(6, p0, p1, p2, p3, true, p4) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
