package topcoder;
import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM755_Div1_L1_OneHandSort
{
	public int[] sortShelf(int[] target)
	{
		ArrayList<Integer> al = new ArrayList<>();
		int n = target.length;
		int[] t = new int[n+1];
		for (int i = 0; i < n; i++) t[i] = target[i];
		n++;
		int empty = n-1;
		t[empty] = -1;
		boolean moved1 = true;
		while (moved1) {
			moved1 = false;
			for (int i = 0; i < n; i++) {
				if (i == n-1 && empty == n-1) break;
				if (empty == n-1) {
					if (t[i] != i) {
						t[empty] = t[i];
						al.add(i);
						empty = i;
						t[empty] = i;
						moved1 = true;
					}
				} else {
					if (t[i] == empty) {
						al.add(i);
						empty = i;
						t[empty] = i;
						moved1 = true;
					}
				}
			}
		}
		int[] ans = new int[al.size()];
		for (int i = 0; i < al.size(); i++) ans[i] = al.get(i);
		return ans;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, boolean hasAnswer, int[] p1) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}");
		System.out.println("]");
		SRM755_Div1_L1_OneHandSort obj;
		int[] answer;
		obj = new SRM755_Div1_L1_OneHandSort();
		long startTime = System.currentTimeMillis();
		answer = obj.sortShelf(p0);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p1.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print(p1[i]);
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(answer[i]);
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p1.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (answer[i] != p1[i]) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int[] p1;
		
		// ----- test 0 -----
		p0 = new int[]{0,1,2};
		p1 = new int[]{};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{1,2,3,0};
		p1 = new int[]{2,1,0,3,4};
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{1,0,3,2};
		p1 = new int[]{0,1,4,2,3,4};
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 0 -----
		p0 = new int[]{0};
		p1 = new int[]{};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 0 -----
		p0 = new int[]{1,0};
		p1 = new int[]{0,1,2};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 0 -----
		p0 = new int[]{0,1,2,3,5,4,7,6};
		p1 = new int[]{4,5,8,6,7,8};
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
