package topcoder;
//import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM770_Div2_L2_LayeredGlass
{
	public int minDefects(String[] a, String[] b)
	{
		int minDefects = Integer.MAX_VALUE;
		
		int cnt = 0;
		
		for (int i = 0; i < 2; i++) {
			if (i == 1) {
				b = flip(b);
			}
			for (int rot = 0; rot < 4; rot++) {
				cnt = getDefects(a,b,rot);
				minDefects = Math.min(cnt, minDefects);
			}
		}
		
		return minDefects;
	}
	
	public String[] flip(String[] b) {
		int n = b.length;
		char[][] c = new char[n][n];
		for (int i = 0; i < n; i++) 
			for (int j = 0; j <= n/2; j++) {
				c[i][j] = b[i].charAt(n-1 - j);
				c[i][n-1 - j] = b[i].charAt(j);
			}
		
		for (int i = 0; i < n; i++)
			b[i] = new String(c[i]);
		return b;		
	}
	
	public int getDefects(String[] a, String[] b, int rot) {
		int n = a.length;
		
		int cnt = 0, i2 = 0, j2 = 0;
		for (int i = 0; i < n; i++) 
			for (int j = 0; j < n; j++) {
				i2 = i; j2 = j;
				for (int k = 0; k < rot; k++) {
					int i2temp = j2; 
					j2 = n-1 - i2;
					i2 = i2temp;
				}
				if (a[i].charAt(j) == 'X' || b[i2].charAt(j2) == 'X') cnt++;
			}
		return cnt;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, String[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p1[i] + "\"");
		}
		System.out.print("}");
		System.out.println("]");
		SRM770_Div2_L2_LayeredGlass obj;
		int answer;
		obj = new SRM770_Div2_L2_LayeredGlass();
		long startTime = System.currentTimeMillis();
		answer = obj.minDefects(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		String[] p1;
		int p2;
		
		// ----- test 0 -----
		p0 = new String[]{"X.",".."};
		p1 = new String[]{"..",".X"};
		p2 = 1;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"...","..X","..."};
		p1 = new String[]{"X..","...","..."};
		p2 = 2;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"...","...","..."};
		p1 = new String[]{"...",".XX","..."};
		p2 = 2;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{".XX","...","..."};
		p1 = new String[]{"X..","...","X.."};
		p2 = 3;
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{"XX..","X...","XX..","X..."};
		p1 = new String[]{"XXXX","X.X.","....","...."};
		p2 = 6;
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 0 -----
		p0 = new String[]{".",};
		p1 = new String[]{"X"};
		p2 = 1;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
