package topcoder;
//import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class SRM797_Div2_L2_OrganicChemistry
{
	public int countHydrogens(String atoms, int[] X, int[] Y)
	{
		int n = atoms.length();
		int m = X.length;
		int[] a = new int [n];
		for (int i = 0; i < m; i++) {
			a[X[i]]++;
			a[Y[i]]++;
		}
		int tot = 0;
		for (int i = 0; i < n; i++) {
			char c = atoms.charAt(i);
			int con = 0;
			if (c == 'C') con = 4;
			else if (c == 'N') con = 3;
			else if (c == 'O') con = 2;
			tot += (con - a[i]);			
		}
		return tot;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String p0, int[] p1, int[] p2, boolean hasAnswer, int p3) {
		System.out.print("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p2.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p2[i]);
		}
		System.out.print("}");
		System.out.println("]");
		SRM797_Div2_L2_OrganicChemistry obj;
		int answer;
		obj = new SRM797_Div2_L2_OrganicChemistry();
		long startTime = System.currentTimeMillis();
		answer = obj.countHydrogens(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p3);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p3;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String p0;
		int[] p1;
		int[] p2;
		int p3;
		
		// ----- test 0 -----
		p0 = "O";
		p1 = new int[]{};
		p2 = new int[]{};
		p3 = 2;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = "C";
		p1 = new int[]{};
		p2 = new int[]{};
		p3 = 4;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = "CCO";
		p1 = new int[]{0,1};
		p2 = new int[]{1,2};
		p3 = 6;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = "CC";
		p1 = new int[]{0,0};
		p2 = new int[]{1,1};
		p3 = 4;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = "OO";
		p1 = new int[]{1,1};
		p2 = new int[]{0,0};
		p3 = 0;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = "OOO";
		p1 = new int[]{0,1,2};
		p2 = new int[]{1,2,0};
		p3 = 0;
		all_right = KawigiEdit_RunTest(5, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 6 -----
		p0 = "CCCCCC";
		p1 = new int[]{0,1,2,3,5,4};
		p2 = new int[]{1,2,3,4,0,5};
		p3 = 12;
		all_right = KawigiEdit_RunTest(6, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 7 -----
		p0 = "CCCCCC";
		p1 = new int[]{0,0,1,2,3,5,4,4,3};
		p2 = new int[]{1,1,2,3,4,0,5,5,2};
		p3 = 6;
		all_right = KawigiEdit_RunTest(7, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 8 -----
		p0 = "CCN";
		p1 = new int[]{0,1};
		p2 = new int[]{2,2};
		p3 = 7;
		all_right = KawigiEdit_RunTest(8, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 8B -----
		p0 = "CCNCCN";
		p1 = new int[]{0,1,3,4};
		p2 = new int[]{2,2,5,5};
		p3 = 14;
		all_right = KawigiEdit_RunTest(8, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
