package topcoder;
import java.util.*;
//import java.util.regex.*;
//import java.text.*;
//import java.math.*;


public class TCO17_L1_PingPongQueue
{
	public int[] whoPlaysNext(int[] skills, int N, int K)
	{
		int n = skills.length;
		int[] win = new int[51];
		ArrayList<Integer> al = new ArrayList<Integer>();
		for (int i = 0; i < n; i++)
			al.add(skills[i]);
		
		int p0 = -1, p1 = -1;
		for (int game = 1; game <= K; game++)
		{
			p0 = al.get(0);
			p1 = al.get(1);
			System.out.println(p0 + " " + p1);
			if (p0 > p1)
			{
				al.remove(1);
				al.add(p1);
				win[p1] = 0;
				win[p0]++;
				if (win[p0] == N)
				{
					al.remove(0);
					al.add(p0);
					win[p0] = 0;
				}
			}
			else
			{
				al.remove(0);
				al.add(p0);
				win[p0] = 0;
				win[p1]++;
				if (win[p1] == N)
				{
					al.remove(0);
					al.add(p1);
					win[p1] = 0;
				}			
			}
		}
		int w = Math.max(p0, p1), l = Math.min(p0, p1);
		int[] ans = new int[]{l, w};
		return ans;
	}
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int p1, int p2, boolean hasAnswer, int[] p3) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + p1 + "," + p2);
		System.out.println("]");
		TCO17_L1_PingPongQueue obj;
		int[] answer;
		obj = new TCO17_L1_PingPongQueue();
		long startTime = System.currentTimeMillis();
		answer = obj.whoPlaysNext(p0, p1, p2);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.print("\t" + "{");
			for (int i = 0; p3.length > i; ++i) {
				if (i > 0) {
					System.out.print(",");
				}
				System.out.print(p3[i]);
			}
			System.out.println("}");
		}
		System.out.println("Your answer:");
		System.out.print("\t" + "{");
		for (int i = 0; answer.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(answer[i]);
		}
		System.out.println("}");
		if (hasAnswer) {
			if (answer.length != p3.length) {
				res = false;
			} else {
				for (int i = 0; answer.length > i; ++i) {
					if (answer[i] != p3[i]) {
						res = false;
					}
				}
			}
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		int[] p0;
		int p1;
		int p2;
		int[] p3;
		
		// ----- test 0 -----
		p0 = new int[]{1,2,3};
		p1 = 2;
		p2 = 2;
		p3 = new int[]{2,3};
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new int[]{1,2,3};
		p1 = 2;
		p2 = 4;
		p3 = new int[]{1,2};
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new int[]{49,24,26,12,5,33,25,30,35,41,46,23,21,3,38,43,11,19,34,29,20,32,39,7,50};
		p1 = 10;
		p2 = 399;
		p3 = new int[]{12,50};
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{30,12};
		p1 = 34;
		p2 = 80;
		p3 = new int[]{12,30};
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new int[]{30,12};
		p1 = 1;
		p2 = 1;
		p3 = new int[]{12,30};
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
